baseURL: 'https://bookmark.yungen.dev/'
languageCode: 'en-us'
title: 'My Bookmark'
menu:
  main:
  - name: tags
    url: /tags/
  - name: bookmarks
    url: /bookmarks/
  - name: categories
    url: /categories/
paginate: 5
taxonomies:
  category: categories
  tag: tags
